In [ ]:
print("day-3")

day-3


In [3]:
#declare Touple
t1=(1,2,3,4.4,"ntt")
print (t1)
print (type(t1))

(1, 2, 3, 4.4, 'ntt')
<class 'tuple'>


In [6]:
#Contructor Tuple

t2=tuple((1,2,3,4.4,"ntt"))
print (t2)

(1, 2, 3, 4.4, 'ntt')


In [7]:
#Contructor Tuple in list
t2=tuple([1,2,3,4.4,"ntt"])
print (t2)

(1, 2, 3, 4.4, 'ntt')


In [11]:
#String Tuple
t4=tuple(("ntt","str"))
print (t4)


('ntt', 'str')


In [12]:
t5=(15)
print (t5)

15


In [20]:
#Accessing Tuple
t6=(10,203,30,34,45)
print(t6[2])
print(t6[2:4])
print(t6[-4:-2:1])

30
(30, 34)
(203, 30)


In [22]:
#If
if 203 in t6:
  print("yes")
else:
    print("no")

yes


In [25]:
#convert tuple into list, list to tuple
t7=(10,203,30,34,45)
t8=[t7]
print(t8)
print(type(t8))

[(10, 203, 30, 34, 45)]
<class 'list'>


In [33]:
#Dictionary
d1={"name":"akash","Roll":1001,"class": 5}
print(d1["Roll"])
print(len(d1))
x=d1.keys()
print(x)
y=d1.values()
print(y)
z=d1.items()
print(z)
d1["name"]="clara"
print(d1)

1001
3
dict_keys(['name', 'Roll', 'class'])
dict_values(['akash', 1001, 5])
dict_items([('name', 'akash'), ('Roll', 1001), ('class', 5)])
{'name': 'clara', 'Roll': 1001, 'class': 5}


In [37]:
#Numpy PAckage
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr)) #type
print(arr.ndim) #dimension
print(arr.size) #size
print(arr.shape) #Shape
print(arr.dtype) #datatype


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
6
(6,)
int64


In [40]:
arr2= np.array([[1,2,3,4],[7,9,9,10]])
print(arr2)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.ndim)

[[ 1  2  3  4]
 [ 7  9  9 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
